### ISSUE TITLE
Update node version to latest

### ISSUE THREAD

**Issue by toddmedema** [toddmedema/electrify#49]
I built the MVP game 5 years ago (how time flies!) and it still works and can be developed on, but it's probably a good idea to update dependencies / modernize it...

Updating the node version in particular to the latest will drive a lot of other package updates

**Comment by n-hebert** [comment]
I'd recommend splitting out any modernizations to specific tickets, but a dependency update ticket like this sounds okay.
Have you taken a look at dependendabot's pull requests? They can usually be merged without too much oversight; it's quite good at what it does.
I'm not familiar with how much automation you have outside of the repo, but if there aren't any automatic pipelines that launch, I'd say you could merge them all in (one at a time or in bulk), test the target locally, and then redeploy.
That would be a great first step on this one.

Are there any other targets to hit for dependency updates?
Maybe an `npm outdated` could help? https://www.freecodecamp.org/news/how-to-update-npm-dependencies/

**Comment by toddmedema** [comment]
Good point, made this ticket more specific, to just deal with the 20+ dependabot PRs. Updating major versions like node version can be future work

**Comment by toddmedema** [comment]
save point: errored on cheerio, seeing if I can remove
