### ISSUE TITLE
Integrate "Learn to Play" and "New Game" modes

### ISSUE THREAD

**Issue by n-hebert** [toddmedema/electrify#51]
## Task: Eliminate the "Learn to Play" and "New Game" distinction

These can take the form of a flat level list where the player can freely interact with the early or later levels as desired.
The priority (first appearance) of the "Learn to Play" sections will drive players to interact with the tutorial levels first.

These can optionally be titled as "Special Scenario" or "Tutorial Scenarios" if appropriate, using a divider within the list for most visual appeal.

## Quote from #45 
> As an "easy to say, hard to do" big one, I would suggest an overhaul which eliminates the "Learn to play" mode entirely. These should just be the first missions. Ready for my opinionated take? 😃
>
> As a life-long gamer I found it kind of hard to immediately tell the mapping between the scenarios and the tutorials. I would ideally want to jump in feet first and learn on the ground, but I'm immediately faced with a choice I don't understand. When I regress to enter the tutorial, it's a lot of pop-up boxes that don't let me test my knowledge. There's currently a heavy weight of "tell don't play" which needs to be reversed to "play don't tell". A way that some game designers really make head-way in this space is to imagine that someone said "We need to ship this to [foreign country] next week and there's no budget to localize any text. Go." Knowing that you can't use any text, you'd start to swap out for symbols. Rendering pictorial/ideographic game prompts for any and all textual representations and slowly training on the meaning of those symbols is the means of eliminating these text prompts.
>
> Not an easy idea, but I believe a low barrier to entry is critical for any game looking to get off the ground.

**Comment by toddmedema** [comment]
Good idea on merging the tutorials into the scenarios, that seems like a really easy starting point!

One thing I liked from playing Against the Storm is that there was no choice - the first few games you play are simplified scenarios.

My one concern over totally gating players based on what they've played is that I don't want the game to require an account, so there should be some clear way to say "I've already done the intro scenarios, take me to the full game"

**Comment by n-hebert** [comment]
Against the Storm sounds like it has the exact idea I'm talking about :slightly_smiling_face: 
 
I definitely agree that we should not gate players at all.
That's especially what I meant by `can freely interact with the early or later levels as desired.` :wink: 

Having a visual divider and not adding those sessions to any "%complete" value can make them entirely skippable. A toggle to hide those into a collapsible heading should neatly get them out of the way for "expert players". If the game grows to a point where they don't even want the header, we can have a second "dismiss" button that can hide it into the options

**Comment by toddmedema** [comment]
Closing, as I think https://github.com/toddmedema/electrify/pull/87 achieved this sufficiently for now
