### ISSUE TITLE
Adjust `Yes/No` user interface semantics on title screen `Enable Music` choice

### ISSUE THREAD

**Issue by n-hebert** [toddmedema/electrify#90]
This looks a bit like a radio button set where the Yes is the default selection and hitting play will enable the music.
In the case, it's actually that you need to hit yes.

# Suggested Fix
Remove the `no` button, as it's default and will imply that no music will occur if Yes is not tapped

**Comment by toddmedema** [comment]
Also noticed some user confusion over the other menu options being hidden until this was interacted with, so going to stop that / show all menu options, and change this to be an "enable music" button
